### ISSUE TITLE
Db created in the wrong place

### ISSUE THREAD

**Issue by jdeath** [njic/medassist#1]
Nice program. The database gets created in `/app/` if the file `/app/medassist/medication.db` does not exist. So data does not persist. If you make a empty file called `medication.db` in `/app/medassist/` the the software will use it and data persists if you mount `/app/medassist/`  as directed in the readme

```
const dockerPath = '/app/medassist/medication.db';
const localPath = './medication.db';
const dbPath = fs.existsSync(dockerPath) ? dockerPath : localPath;
```

**Comment by jdeath** [comment]
I am not 100% sure, you are way better coder than me. I would say one version would be better, less to maintain. A note in the readme might be sufficient. Another option for docker is have an environment variable where the user passes in a database location. No environment variable, use your default. I'll try the next release when you pick a solution.

**Comment by njic** [comment]
I'm flattered :D

New release is up and I'm closing the first issue WOOOP! Thanks again
