### ISSUE TITLE
Add suport arm servers

### ISSUE THREAD

**Issue by John710** [njic/medassist#17]
Hello! My small home server is Raspberry Pi 5, and i need arm image(

**Comment by njic** [comment]
Hey dude, I've already received that request on other platforms. I've tried running it on my pi4 and I did some research. Seems like it's easy to fix and you can expect arm support soon!

Thx for opening the issue

**Comment by njic** [comment]
If you are using docker try this image

ghcr.io/njic/medassist:v0.16.0.develop

This one should support all architectures, but feels like image size is huge. I'll probably push an image for each architecture from now on. I need to figure how to reduce image size anyway.

Please try it and let me know does it work for you. It took like 4-5 min on my Rpi4 to download and deploy, but its running smooth so far

**Comment by John710** [comment]
> try this image

Yes, it works. To reduce the size, you can use the alpine version of node.
I'm not sure if I'm right, but it usually noticeably reduces the weight of the image. The regular version weighs 300 MB, and the alpine version weighs 50 MB.

**Comment by njic** [comment]
Thank you! Ill check other versions of node.

Closing issue woop!
